# Generated by Django 2.1.4 on 2018-12-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typehall', models.CharField(max_length=10)),
                ('seatsnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdt', models.DateTimeField()),
                ('form', models.CharField(default='2D', max_length=3)),
                ('filmid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Film')),
                ('hallid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond', models.CharField(default='free', max_length=10)),
                ('price', models.CharField(default='100 rub', max_length=10)),
                ('sessionid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Session')),
            ],
        ),
    ]
